### ISSUE TITLE
Presets?

### ISSUE THREAD

**Issue by kevinSuttle** [editorconfig/editorconfig#245]
Thinking about https://github.com/editorconfig/editorconfig-core-js/issues/30, it would be handy to have a collection of presets. 
##

**Comment by xuhdev** [comment]
Can you explain a bit more? I don't understand your point on the `js` package (p.s. I'm not familiar with js)

**Comment by kevinSuttle** [comment]
So, instead of having a separate [.eslintrc](http://eslint.org/docs/user-guide/configuring#configuration-file-formats) file, there are defined presets that can be leveraged via custom configuration objects in package.json, [like Gemfile, requirements.txt, etc., but for JS]. 

Example from airbnb: https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**package.json**
eslintConfig
{
   "extends": "airbnb/base"
}

**Comment by sindresorhus** [comment]
:+1: !!

I have [this file](https://github.com/sindresorhus/ava/blob/ff5b8dfa5cc9c49a0919c9cad0896cb9c3e971ee/.editorconfig) duplicated in hundreds of repos...

**Comment by kevinSuttle** [comment]
:point_up: Yep. That's exactly the problem I'm hoping to solve.

**Comment by xuhdev** [comment]
It makes sense for me. This seems like a editorconfig-core-js specific issue.... Can we move the discussion there?

**Comment by kevinSuttle** [comment]
Done. :octocat: https://github.com/editorconfig/editorconfig-core-js/issues/31

**Comment by sindresorhus** [comment]
It's not specific to JS. That was just an example. For presets to be actually usable, they need to be supported by all EditorConfig implementations, not just the JS one. It should work even if I for example use the EditorConfig Sublime plugin.

I'm thinking:

```ini
# .editorconfig
extends = path/to/folder/containing/editorconfig/file
```

-

*(Putting EditorConfig config into package.json should be a separate issue, on this issue tracker, as it also pertains to all implementation).*

**Comment by kevinSuttle** [comment]
@sindresorhus I'm all for consolidation. What about a global in `~/.config`?

**Comment by sindresorhus** [comment]
@kevinSuttle That doesn't really solve my issue of having to put an `.editorconfig` file in every repo. The point is that other users follows it, not me. You can already put a `.editorconfig` file in `~/` if you don't put `root = true` in your local `.editorconfig` files.

**Comment by kevinSuttle** [comment]
Ah, I did not know that. I was thinking more of the global `~/.gitignore` and `~/.npmrc` so an `.editorconfig` file doesn't _have_ to be present in every repo. 

But I see your point about ensuring others follow suit and apply the same settings when the repo is distributed.

**Comment by xuhdev** [comment]
I agree with @sindresorhus , it is exactly the reason we don't support a "global" configuration file.

@sindresorhus If we have an "extends" or "include" instruction, is the `package.json` issue still relevant?

**Comment by kevinSuttle** [comment]
@xuhdev Yes. See above https://github.com/editorconfig/editorconfig/issues/245#issuecomment-163032924

**Comment by sindresorhus** [comment]
> If we have an "extends" or "include" instruction, is the package.json issue still relevant?

Yes, but that's a discussion for a different issue, but tl;dr; I have so many metafiles (.editorconfig, .gitignore, .gitattributes, etc) in my repos and I would like to reduce that number. Would be nice if I could define EditorConfig config in package.json instead of an .editorconfig file, since I almost always have a package.json file in my repos. Many other tools supports this.

**Comment by jpolo** [comment]
One useful usecase could be to commit a "company" wide editorconfig so it is not global for the computer but just the company repos.
For a node project the common way would be to publish an npm package containing the editorconfig preset and to add an extends/include/whatever instruction in the .editorconfig file to 'node_modules/mycompany-editorconfig/.editorconfig'

**Comment by openjck** [comment]
Is this a duplicate of #236?

**Comment by cxw42** [comment]
If @sindresorhus indeed reopened the issue for https://github.com/editorconfig/editorconfig/issues/245#issuecomment-163789839, then, yes, it looks like a duplicate of #236.

**Comment by cxw42** [comment]
Hearing nothing to the contrary,  I am going to re-close this as duplicate to keep the discussion centralized in #236.
